# Generated by Django 6.0.4 on 2026-04-25 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('inn', models.CharField(max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.client')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Ожидается'), ('uploaded', 'Загружен'), ('brought_personally', 'Принесён лично'), ('not_required', 'Не требуется'), ('verified', 'Проверен'), ('rejected', 'Отклонен')], default='waiting', max_length=30)),
                ('comment', models.TextField(blank=True, null=True)),
                ('client_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='documents.clientcase')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.documenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('extracted_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('extracted_inn', models.CharField(blank=True, max_length=12, null=True)),
                ('extracted_document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('required_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='documents.requireddocument')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('required_documents', models.ManyToManyField(blank=True, related_name='services', to='documents.documenttype')),
            ],
        ),
        migrations.AddField(
            model_name='clientcase',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.servicetype'),
        ),
    ]
